source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

# Settings
inhibit_all_warnings!
use_frameworks!

# use_frameworks! :linkage => :static

# pod 'AppLovinSDK', '12.4.1'
# pod 'GoogleMobileAdsMediationAppLovin', '12.4.0.0'
pod 'GoogleMobileAdsMediationPangle', '5.9.0.9.0'

# pod 'GoogleMobileAdsMediationAppLovin'